[tasks.build]
description = "Build the CLI"
run = "go build -ldflags \"-X main.version=$(git rev-parse --short HEAD)\" ."

[tasks.ge]
description = "Run the code"
run = "go run ."

[tasks.gu]
description = "Update all dependencies"
run = "go get -u"
